// <auto-generated />
using ItemPriceCharts.Services.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItemPriceCharts.Services.Migrations
{
    [DbContext(typeof(ModelsContext))]
    [Migration("20200729204543_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ItemPriceCharts.Services.Models.ItemModel", b =>
                {
                    b.Property<int>("ItemtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineShopModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemtId");

                    b.HasIndex("OnlineShopModelId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ItemPriceCharts.Services.Models.OnlineShopModel", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("OnlineShops");
                });

            modelBuilder.Entity("ItemPriceCharts.Services.Models.ItemModel", b =>
                {
                    b.HasOne("ItemPriceCharts.Services.Models.OnlineShopModel", "OnlineShop")
                        .WithMany("Items")
                        .HasForeignKey("OnlineShopModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
